// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"review-c/internal/biz"
	"review-c/internal/conf"
	"review-c/internal/data"
	"review-c/internal/server"
	"review-c/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, security *conf.Security, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer, logger)
	discovery := data.NewDiscovery(registry, logger)
	reviewClient, cleanup, err := data.NewReviewServiceClient(confData, discovery, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(reviewClient, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	consumerRepo := data.NewConsumerRepo(dataData, logger)
	consumerUsecase := biz.NewConsumerUsecase(consumerRepo, logger)
	consumerService := service.NewConsumerService(consumerUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, security, consumerService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
