// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.20.3
// source: api/consumer/v1/consumer.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationConsumerCreateReview = "/api.consumer.v1.Consumer/CreateReview"
const OperationConsumerGetReview = "/api.consumer.v1.Consumer/GetReview"
const OperationConsumerListReviewByUserID = "/api.consumer.v1.Consumer/ListReviewByUserID"
const OperationConsumerListReviews = "/api.consumer.v1.Consumer/ListReviews"

type ConsumerHTTPServer interface {
	// CreateReview [REQ-001] C 端创建评价（按 order_id 幂等，下游保证）
	CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewReply, error)
	// GetReview [REQ-002] C 端查看评价详情（非 APPROVED 会被下游折叠为 NotFound；匿名评价 user_id=0）
	GetReview(context.Context, *GetReviewRequest) (*GetReviewReply, error)
	// ListReviewByUserID [REQ-003] C 端"我的评价"列表（含待审/驳回状态，下游按 role=C 隐式处理）
	ListReviewByUserID(context.Context, *ListReviewByUserIDRequest) (*ListReviewByUserIDReply, error)
	// ListReviews [REQ-003] C 端按条件列表（仅 APPROVED；筛选子集见下方 ListReviewsRequest）
	ListReviews(context.Context, *ListReviewsRequest) (*ListReviewsReply, error)
}

func RegisterConsumerHTTPServer(s *http.Server, srv ConsumerHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/reviews", _Consumer_CreateReview0_HTTP_Handler(srv))
	r.GET("/v1/reviews/{review_id}", _Consumer_GetReview0_HTTP_Handler(srv))
	r.GET("/v1/users/{user_id}/reviews", _Consumer_ListReviewByUserID0_HTTP_Handler(srv))
	r.GET("/v1/reviews", _Consumer_ListReviews0_HTTP_Handler(srv))
}

func _Consumer_CreateReview0_HTTP_Handler(srv ConsumerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateReviewRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsumerCreateReview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateReview(ctx, req.(*CreateReviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateReviewReply)
		return ctx.Result(200, reply)
	}
}

func _Consumer_GetReview0_HTTP_Handler(srv ConsumerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReviewRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsumerGetReview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReview(ctx, req.(*GetReviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetReviewReply)
		return ctx.Result(200, reply)
	}
}

func _Consumer_ListReviewByUserID0_HTTP_Handler(srv ConsumerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListReviewByUserIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsumerListReviewByUserID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListReviewByUserID(ctx, req.(*ListReviewByUserIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListReviewByUserIDReply)
		return ctx.Result(200, reply)
	}
}

func _Consumer_ListReviews0_HTTP_Handler(srv ConsumerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListReviewsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConsumerListReviews)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListReviews(ctx, req.(*ListReviewsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListReviewsReply)
		return ctx.Result(200, reply)
	}
}

type ConsumerHTTPClient interface {
	// CreateReview [REQ-001] C 端创建评价（按 order_id 幂等，下游保证）
	CreateReview(ctx context.Context, req *CreateReviewRequest, opts ...http.CallOption) (rsp *CreateReviewReply, err error)
	// GetReview [REQ-002] C 端查看评价详情（非 APPROVED 会被下游折叠为 NotFound；匿名评价 user_id=0）
	GetReview(ctx context.Context, req *GetReviewRequest, opts ...http.CallOption) (rsp *GetReviewReply, err error)
	// ListReviewByUserID [REQ-003] C 端"我的评价"列表（含待审/驳回状态，下游按 role=C 隐式处理）
	ListReviewByUserID(ctx context.Context, req *ListReviewByUserIDRequest, opts ...http.CallOption) (rsp *ListReviewByUserIDReply, err error)
	// ListReviews [REQ-003] C 端按条件列表（仅 APPROVED；筛选子集见下方 ListReviewsRequest）
	ListReviews(ctx context.Context, req *ListReviewsRequest, opts ...http.CallOption) (rsp *ListReviewsReply, err error)
}

type ConsumerHTTPClientImpl struct {
	cc *http.Client
}

func NewConsumerHTTPClient(client *http.Client) ConsumerHTTPClient {
	return &ConsumerHTTPClientImpl{client}
}

// CreateReview [REQ-001] C 端创建评价（按 order_id 幂等，下游保证）
func (c *ConsumerHTTPClientImpl) CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...http.CallOption) (*CreateReviewReply, error) {
	var out CreateReviewReply
	pattern := "/v1/reviews"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConsumerCreateReview))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetReview [REQ-002] C 端查看评价详情（非 APPROVED 会被下游折叠为 NotFound；匿名评价 user_id=0）
func (c *ConsumerHTTPClientImpl) GetReview(ctx context.Context, in *GetReviewRequest, opts ...http.CallOption) (*GetReviewReply, error) {
	var out GetReviewReply
	pattern := "/v1/reviews/{review_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsumerGetReview))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListReviewByUserID [REQ-003] C 端"我的评价"列表（含待审/驳回状态，下游按 role=C 隐式处理）
func (c *ConsumerHTTPClientImpl) ListReviewByUserID(ctx context.Context, in *ListReviewByUserIDRequest, opts ...http.CallOption) (*ListReviewByUserIDReply, error) {
	var out ListReviewByUserIDReply
	pattern := "/v1/users/{user_id}/reviews"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsumerListReviewByUserID))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListReviews [REQ-003] C 端按条件列表（仅 APPROVED；筛选子集见下方 ListReviewsRequest）
func (c *ConsumerHTTPClientImpl) ListReviews(ctx context.Context, in *ListReviewsRequest, opts ...http.CallOption) (*ListReviewsReply, error) {
	var out ListReviewsReply
	pattern := "/v1/reviews"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConsumerListReviews))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
