// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: api/consumer/v1/consumer.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewStatus int32

const (
	ReviewStatus_REVIEW_STATUS_UNSPECIFIED ReviewStatus = 0
	ReviewStatus_REVIEW_STATUS_PENDING     ReviewStatus = 10
	ReviewStatus_REVIEW_STATUS_APPROVED    ReviewStatus = 20
	ReviewStatus_REVIEW_STATUS_REJECTED    ReviewStatus = 30
	ReviewStatus_REVIEW_STATUS_HIDDEN      ReviewStatus = 40
)

// Enum value maps for ReviewStatus.
var (
	ReviewStatus_name = map[int32]string{
		0:  "REVIEW_STATUS_UNSPECIFIED",
		10: "REVIEW_STATUS_PENDING",
		20: "REVIEW_STATUS_APPROVED",
		30: "REVIEW_STATUS_REJECTED",
		40: "REVIEW_STATUS_HIDDEN",
	}
	ReviewStatus_value = map[string]int32{
		"REVIEW_STATUS_UNSPECIFIED": 0,
		"REVIEW_STATUS_PENDING":     10,
		"REVIEW_STATUS_APPROVED":    20,
		"REVIEW_STATUS_REJECTED":    30,
		"REVIEW_STATUS_HIDDEN":      40,
	}
)

func (x ReviewStatus) Enum() *ReviewStatus {
	p := new(ReviewStatus)
	*p = x
	return p
}

func (x ReviewStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_consumer_v1_consumer_proto_enumTypes[0].Descriptor()
}

func (ReviewStatus) Type() protoreflect.EnumType {
	return &file_api_consumer_v1_consumer_proto_enumTypes[0]
}

func (x ReviewStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewStatus.Descriptor instead.
func (ReviewStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{0}
}

type AppealStatus int32

const (
	AppealStatus_APPEAL_STATUS_UNSPECIFIED AppealStatus = 0
	AppealStatus_APPEAL_STATUS_PENDING     AppealStatus = 10
	AppealStatus_APPEAL_STATUS_APPROVED    AppealStatus = 20
	AppealStatus_APPEAL_STATUS_REJECTED    AppealStatus = 30
)

// Enum value maps for AppealStatus.
var (
	AppealStatus_name = map[int32]string{
		0:  "APPEAL_STATUS_UNSPECIFIED",
		10: "APPEAL_STATUS_PENDING",
		20: "APPEAL_STATUS_APPROVED",
		30: "APPEAL_STATUS_REJECTED",
	}
	AppealStatus_value = map[string]int32{
		"APPEAL_STATUS_UNSPECIFIED": 0,
		"APPEAL_STATUS_PENDING":     10,
		"APPEAL_STATUS_APPROVED":    20,
		"APPEAL_STATUS_REJECTED":    30,
	}
)

func (x AppealStatus) Enum() *AppealStatus {
	p := new(AppealStatus)
	*p = x
	return p
}

func (x AppealStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppealStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_consumer_v1_consumer_proto_enumTypes[1].Descriptor()
}

func (AppealStatus) Type() protoreflect.EnumType {
	return &file_api_consumer_v1_consumer_proto_enumTypes[1]
}

func (x AppealStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppealStatus.Descriptor instead.
func (AppealStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{1}
}

type ReviewSort int32

const (
	ReviewSort_REVIEW_SORT_UNSPECIFIED      ReviewSort = 0
	ReviewSort_REVIEW_SORT_CREATE_TIME_DESC ReviewSort = 1
	ReviewSort_REVIEW_SORT_SCORE_ASC        ReviewSort = 2
	ReviewSort_REVIEW_SORT_SCORE_DESC       ReviewSort = 3
)

// Enum value maps for ReviewSort.
var (
	ReviewSort_name = map[int32]string{
		0: "REVIEW_SORT_UNSPECIFIED",
		1: "REVIEW_SORT_CREATE_TIME_DESC",
		2: "REVIEW_SORT_SCORE_ASC",
		3: "REVIEW_SORT_SCORE_DESC",
	}
	ReviewSort_value = map[string]int32{
		"REVIEW_SORT_UNSPECIFIED":      0,
		"REVIEW_SORT_CREATE_TIME_DESC": 1,
		"REVIEW_SORT_SCORE_ASC":        2,
		"REVIEW_SORT_SCORE_DESC":       3,
	}
)

func (x ReviewSort) Enum() *ReviewSort {
	p := new(ReviewSort)
	*p = x
	return p
}

func (x ReviewSort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewSort) Descriptor() protoreflect.EnumDescriptor {
	return file_api_consumer_v1_consumer_proto_enumTypes[2].Descriptor()
}

func (ReviewSort) Type() protoreflect.EnumType {
	return &file_api_consumer_v1_consumer_proto_enumTypes[2]
}

func (x ReviewSort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewSort.Descriptor instead.
func (ReviewSort) EnumDescriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{2}
}

type PaginationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationReply) Reset() {
	*x = PaginationReply{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationReply) ProtoMessage() {}

func (x *PaginationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationReply.ProtoReflect.Descriptor instead.
func (*PaginationReply) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ReviewSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 匿名评价在 C 端返回时为 0（下游 review-service 脱敏）
	StoreId       int64                  `protobuf:"varint,4,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	SkuId         int64                  `protobuf:"varint,5,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SpuId         int64                  `protobuf:"varint,6,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	Score         int32                  `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`
	ServiceScore  int32                  `protobuf:"varint,8,opt,name=service_score,json=serviceScore,proto3" json:"service_score,omitempty"`
	ExpressScore  int32                  `protobuf:"varint,9,opt,name=express_score,json=expressScore,proto3" json:"express_score,omitempty"`
	Content       string                 `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	Anonymous     bool                   `protobuf:"varint,11,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
	HasMedia      bool                   `protobuf:"varint,12,opt,name=has_media,json=hasMedia,proto3" json:"has_media,omitempty"`
	HasReply      bool                   `protobuf:"varint,13,opt,name=has_reply,json=hasReply,proto3" json:"has_reply,omitempty"`
	IsDefault     bool                   `protobuf:"varint,14,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Status        ReviewStatus           `protobuf:"varint,15,opt,name=status,proto3,enum=api.consumer.v1.ReviewStatus" json:"status,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewSummary) Reset() {
	*x = ReviewSummary{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewSummary) ProtoMessage() {}

func (x *ReviewSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewSummary.ProtoReflect.Descriptor instead.
func (*ReviewSummary) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewSummary) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *ReviewSummary) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReviewSummary) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReviewSummary) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *ReviewSummary) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *ReviewSummary) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *ReviewSummary) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ReviewSummary) GetServiceScore() int32 {
	if x != nil {
		return x.ServiceScore
	}
	return 0
}

func (x *ReviewSummary) GetExpressScore() int32 {
	if x != nil {
		return x.ExpressScore
	}
	return 0
}

func (x *ReviewSummary) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReviewSummary) GetAnonymous() bool {
	if x != nil {
		return x.Anonymous
	}
	return false
}

func (x *ReviewSummary) GetHasMedia() bool {
	if x != nil {
		return x.HasMedia
	}
	return false
}

func (x *ReviewSummary) GetHasReply() bool {
	if x != nil {
		return x.HasReply
	}
	return false
}

func (x *ReviewSummary) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *ReviewSummary) GetStatus() ReviewStatus {
	if x != nil {
		return x.Status
	}
	return ReviewStatus_REVIEW_STATUS_UNSPECIFIED
}

func (x *ReviewSummary) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ReviewSummary) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type ReplyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	ReviewId      int64                  `protobuf:"varint,2,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	StoreId       int64                  `protobuf:"varint,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	PicUrls       []string               `protobuf:"bytes,5,rep,name=pic_urls,json=picUrls,proto3" json:"pic_urls,omitempty"`
	VideoUrls     []string               `protobuf:"bytes,6,rep,name=video_urls,json=videoUrls,proto3" json:"video_urls,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Version       int32                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyInfo) Reset() {
	*x = ReplyInfo{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyInfo) ProtoMessage() {}

func (x *ReplyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyInfo.ProtoReflect.Descriptor instead.
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{2}
}

func (x *ReplyInfo) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *ReplyInfo) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *ReplyInfo) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *ReplyInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyInfo) GetPicUrls() []string {
	if x != nil {
		return x.PicUrls
	}
	return nil
}

func (x *ReplyInfo) GetVideoUrls() []string {
	if x != nil {
		return x.VideoUrls
	}
	return nil
}

func (x *ReplyInfo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ReplyInfo) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *ReplyInfo) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ReviewDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Summary           *ReviewSummary         `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	PicUrls           []string               `protobuf:"bytes,2,rep,name=pic_urls,json=picUrls,proto3" json:"pic_urls,omitempty"`
	VideoUrls         []string               `protobuf:"bytes,3,rep,name=video_urls,json=videoUrls,proto3" json:"video_urls,omitempty"`
	TagsJson          string                 `protobuf:"bytes,4,opt,name=tags_json,json=tagsJson,proto3" json:"tags_json,omitempty"`
	GoodsSnapshotJson string                 `protobuf:"bytes,5,opt,name=goods_snapshot_json,json=goodsSnapshotJson,proto3" json:"goods_snapshot_json,omitempty"`
	Replies           []*ReplyInfo           `protobuf:"bytes,6,rep,name=replies,proto3" json:"replies,omitempty"` // C 端不暴露 ReviewAuditInfo（运营审核元数据对消费者无意义；下游过滤后本层也不回填）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReviewDetail) Reset() {
	*x = ReviewDetail{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewDetail) ProtoMessage() {}

func (x *ReviewDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewDetail.ProtoReflect.Descriptor instead.
func (*ReviewDetail) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{3}
}

func (x *ReviewDetail) GetSummary() *ReviewSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *ReviewDetail) GetPicUrls() []string {
	if x != nil {
		return x.PicUrls
	}
	return nil
}

func (x *ReviewDetail) GetVideoUrls() []string {
	if x != nil {
		return x.VideoUrls
	}
	return nil
}

func (x *ReviewDetail) GetTagsJson() string {
	if x != nil {
		return x.TagsJson
	}
	return ""
}

func (x *ReviewDetail) GetGoodsSnapshotJson() string {
	if x != nil {
		return x.GoodsSnapshotJson
	}
	return ""
}

func (x *ReviewDetail) GetReplies() []*ReplyInfo {
	if x != nil {
		return x.Replies
	}
	return nil
}

// 字段与 review-service.CreateReviewRequest 1:1 对齐；user_id 由 HTTP 中间件校验与 X-User-Id 一致
// （防止 A 用户伪造 B 的订单评价）。
type CreateReviewRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId           int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StoreId           int64                  `protobuf:"varint,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	SkuId             int64                  `protobuf:"varint,4,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SpuId             int64                  `protobuf:"varint,5,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	Score             int32                  `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	ServiceScore      int32                  `protobuf:"varint,7,opt,name=service_score,json=serviceScore,proto3" json:"service_score,omitempty"`
	ExpressScore      int32                  `protobuf:"varint,8,opt,name=express_score,json=expressScore,proto3" json:"express_score,omitempty"`
	Content           string                 `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	PicUrls           []string               `protobuf:"bytes,10,rep,name=pic_urls,json=picUrls,proto3" json:"pic_urls,omitempty"`
	VideoUrls         []string               `protobuf:"bytes,11,rep,name=video_urls,json=videoUrls,proto3" json:"video_urls,omitempty"`
	Anonymous         bool                   `protobuf:"varint,12,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
	TagsJson          string                 `protobuf:"bytes,13,opt,name=tags_json,json=tagsJson,proto3" json:"tags_json,omitempty"`
	GoodsSnapshotJson string                 `protobuf:"bytes,14,opt,name=goods_snapshot_json,json=goodsSnapshotJson,proto3" json:"goods_snapshot_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReviewRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReviewRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateReviewRequest) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *CreateReviewRequest) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CreateReviewRequest) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *CreateReviewRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CreateReviewRequest) GetServiceScore() int32 {
	if x != nil {
		return x.ServiceScore
	}
	return 0
}

func (x *CreateReviewRequest) GetExpressScore() int32 {
	if x != nil {
		return x.ExpressScore
	}
	return 0
}

func (x *CreateReviewRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateReviewRequest) GetPicUrls() []string {
	if x != nil {
		return x.PicUrls
	}
	return nil
}

func (x *CreateReviewRequest) GetVideoUrls() []string {
	if x != nil {
		return x.VideoUrls
	}
	return nil
}

func (x *CreateReviewRequest) GetAnonymous() bool {
	if x != nil {
		return x.Anonymous
	}
	return false
}

func (x *CreateReviewRequest) GetTagsJson() string {
	if x != nil {
		return x.TagsJson
	}
	return ""
}

func (x *CreateReviewRequest) GetGoodsSnapshotJson() string {
	if x != nil {
		return x.GoodsSnapshotJson
	}
	return ""
}

type CreateReviewReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewReply) Reset() {
	*x = CreateReviewReply{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewReply) ProtoMessage() {}

func (x *CreateReviewReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewReply.ProtoReflect.Descriptor instead.
func (*CreateReviewReply) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{5}
}

func (x *CreateReviewReply) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

type GetReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewRequest) Reset() {
	*x = GetReviewRequest{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewRequest) ProtoMessage() {}

func (x *GetReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewRequest.ProtoReflect.Descriptor instead.
func (*GetReviewRequest) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{6}
}

func (x *GetReviewRequest) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

type GetReviewReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *ReviewDetail          `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewReply) Reset() {
	*x = GetReviewReply{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewReply) ProtoMessage() {}

func (x *GetReviewReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewReply.ProtoReflect.Descriptor instead.
func (*GetReviewReply) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{7}
}

func (x *GetReviewReply) GetReview() *ReviewDetail {
	if x != nil {
		return x.Review
	}
	return nil
}

type ListReviewByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewByUserIDRequest) Reset() {
	*x = ListReviewByUserIDRequest{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewByUserIDRequest) ProtoMessage() {}

func (x *ListReviewByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewByUserIDRequest.ProtoReflect.Descriptor instead.
func (*ListReviewByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{8}
}

func (x *ListReviewByUserIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListReviewByUserIDRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReviewByUserIDRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListReviewByUserIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ReviewSummary       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          *PaginationReply       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewByUserIDReply) Reset() {
	*x = ListReviewByUserIDReply{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewByUserIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewByUserIDReply) ProtoMessage() {}

func (x *ListReviewByUserIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewByUserIDReply.ProtoReflect.Descriptor instead.
func (*ListReviewByUserIDReply) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{9}
}

func (x *ListReviewByUserIDReply) GetList() []*ReviewSummary {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListReviewByUserIDReply) GetPage() *PaginationReply {
	if x != nil {
		return x.Page
	}
	return nil
}

// C 端筛选子集：只开放 store_id / spu_id / sku_id / score / has_media / sort / 分页。
// 禁止的字段：user_id（隐私）/ status（下游 role=C 会强制 APPROVED）/ has_reply（内部实现细节）。
// 这些字段即使 proto 里不存在，中间件也不需要额外拦截。
type ListReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       int64                  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	SpuId         int64                  `protobuf:"varint,2,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	SkuId         int64                  `protobuf:"varint,3,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	HasMedia      bool                   `protobuf:"varint,5,opt,name=has_media,json=hasMedia,proto3" json:"has_media,omitempty"`
	Sort          ReviewSort             `protobuf:"varint,6,opt,name=sort,proto3,enum=api.consumer.v1.ReviewSort" json:"sort,omitempty"`
	Page          int32                  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsRequest) Reset() {
	*x = ListReviewsRequest{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsRequest) ProtoMessage() {}

func (x *ListReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsRequest) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{10}
}

func (x *ListReviewsRequest) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *ListReviewsRequest) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *ListReviewsRequest) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *ListReviewsRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ListReviewsRequest) GetHasMedia() bool {
	if x != nil {
		return x.HasMedia
	}
	return false
}

func (x *ListReviewsRequest) GetSort() ReviewSort {
	if x != nil {
		return x.Sort
	}
	return ReviewSort_REVIEW_SORT_UNSPECIFIED
}

func (x *ListReviewsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReviewsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListReviewsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ReviewSummary       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          *PaginationReply       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsReply) Reset() {
	*x = ListReviewsReply{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsReply) ProtoMessage() {}

func (x *ListReviewsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsReply.ProtoReflect.Descriptor instead.
func (*ListReviewsReply) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{11}
}

func (x *ListReviewsReply) GetList() []*ReviewSummary {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListReviewsReply) GetPage() *PaginationReply {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_api_consumer_v1_consumer_proto protoreflect.FileDescriptor

const file_api_consumer_v1_consumer_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/consumer/v1/consumer.proto\x12\x0fapi.consumer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"X\n" +
	"\x0fPaginationReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xcb\x04\n" +
	"\rReviewSummary\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x03R\breviewId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x19\n" +
	"\bstore_id\x18\x04 \x01(\x03R\astoreId\x12\x15\n" +
	"\x06sku_id\x18\x05 \x01(\x03R\x05skuId\x12\x15\n" +
	"\x06spu_id\x18\x06 \x01(\x03R\x05spuId\x12\x14\n" +
	"\x05score\x18\a \x01(\x05R\x05score\x12#\n" +
	"\rservice_score\x18\b \x01(\x05R\fserviceScore\x12#\n" +
	"\rexpress_score\x18\t \x01(\x05R\fexpressScore\x12\x18\n" +
	"\acontent\x18\n" +
	" \x01(\tR\acontent\x12\x1c\n" +
	"\tanonymous\x18\v \x01(\bR\tanonymous\x12\x1b\n" +
	"\thas_media\x18\f \x01(\bR\bhasMedia\x12\x1b\n" +
	"\thas_reply\x18\r \x01(\bR\bhasReply\x12\x1d\n" +
	"\n" +
	"is_default\x18\x0e \x01(\bR\tisDefault\x125\n" +
	"\x06status\x18\x0f \x01(\x0e2\x1d.api.consumer.v1.ReviewStatusR\x06status\x12;\n" +
	"\vcreate_time\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\xc6\x02\n" +
	"\tReplyInfo\x12\x19\n" +
	"\breply_id\x18\x01 \x01(\x03R\areplyId\x12\x1b\n" +
	"\treview_id\x18\x02 \x01(\x03R\breviewId\x12\x19\n" +
	"\bstore_id\x18\x03 \x01(\x03R\astoreId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x19\n" +
	"\bpic_urls\x18\x05 \x03(\tR\apicUrls\x12\x1d\n" +
	"\n" +
	"video_urls\x18\x06 \x03(\tR\tvideoUrls\x12;\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x18\n" +
	"\aversion\x18\t \x01(\x05R\aversion\"\x85\x02\n" +
	"\fReviewDetail\x128\n" +
	"\asummary\x18\x01 \x01(\v2\x1e.api.consumer.v1.ReviewSummaryR\asummary\x12\x19\n" +
	"\bpic_urls\x18\x02 \x03(\tR\apicUrls\x12\x1d\n" +
	"\n" +
	"video_urls\x18\x03 \x03(\tR\tvideoUrls\x12\x1b\n" +
	"\ttags_json\x18\x04 \x01(\tR\btagsJson\x12.\n" +
	"\x13goods_snapshot_json\x18\x05 \x01(\tR\x11goodsSnapshotJson\x124\n" +
	"\areplies\x18\x06 \x03(\v2\x1a.api.consumer.v1.ReplyInfoR\areplies\"\xb3\x04\n" +
	"\x13CreateReviewRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\"\n" +
	"\border_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aorderId\x12\"\n" +
	"\bstore_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\astoreId\x12\x1e\n" +
	"\x06sku_id\x18\x04 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x05skuId\x12\x1e\n" +
	"\x06spu_id\x18\x05 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x05spuId\x12\x1f\n" +
	"\x05score\x18\x06 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x05(\x01R\x05score\x12.\n" +
	"\rservice_score\x18\a \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x05(\x00R\fserviceScore\x12.\n" +
	"\rexpress_score\x18\b \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x05(\x00R\fexpressScore\x12$\n" +
	"\acontent\x18\t \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x04R\acontent\x12#\n" +
	"\bpic_urls\x18\n" +
	" \x03(\tB\b\xfaB\x05\x92\x01\x02\x10\tR\apicUrls\x12'\n" +
	"\n" +
	"video_urls\x18\v \x03(\tB\b\xfaB\x05\x92\x01\x02\x10\x03R\tvideoUrls\x12\x1c\n" +
	"\tanonymous\x18\f \x01(\bR\tanonymous\x12%\n" +
	"\ttags_json\x18\r \x01(\tB\b\xfaB\x05r\x03\x18\x80\bR\btagsJson\x128\n" +
	"\x13goods_snapshot_json\x18\x0e \x01(\tB\b\xfaB\x05r\x03\x18\x80\x10R\x11goodsSnapshotJson\"0\n" +
	"\x11CreateReviewReply\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x03R\breviewId\"8\n" +
	"\x10GetReviewRequest\x12$\n" +
	"\treview_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\breviewId\"G\n" +
	"\x0eGetReviewReply\x125\n" +
	"\x06review\x18\x01 \x01(\v2\x1d.api.consumer.v1.ReviewDetailR\x06review\"\x82\x01\n" +
	"\x19ListReviewByUserIDRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\x1b\n" +
	"\x04page\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x04page\x12&\n" +
	"\tpage_size\x18\x03 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x00R\bpageSize\"\x83\x01\n" +
	"\x17ListReviewByUserIDReply\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.api.consumer.v1.ReviewSummaryR\x04list\x124\n" +
	"\x04page\x18\x02 \x01(\v2 .api.consumer.v1.PaginationReplyR\x04page\"\xb6\x02\n" +
	"\x12ListReviewsRequest\x12\"\n" +
	"\bstore_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\astoreId\x12\x1e\n" +
	"\x06spu_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\x05spuId\x12\x1e\n" +
	"\x06sku_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\x05skuId\x12\x1f\n" +
	"\x05score\x18\x04 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x05(\x00R\x05score\x12\x1b\n" +
	"\thas_media\x18\x05 \x01(\bR\bhasMedia\x129\n" +
	"\x04sort\x18\x06 \x01(\x0e2\x1b.api.consumer.v1.ReviewSortB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04sort\x12\x1b\n" +
	"\x04page\x18\a \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x04page\x12&\n" +
	"\tpage_size\x18\b \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x00R\bpageSize\"|\n" +
	"\x10ListReviewsReply\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.api.consumer.v1.ReviewSummaryR\x04list\x124\n" +
	"\x04page\x18\x02 \x01(\v2 .api.consumer.v1.PaginationReplyR\x04page*\x9a\x01\n" +
	"\fReviewStatus\x12\x1d\n" +
	"\x19REVIEW_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REVIEW_STATUS_PENDING\x10\n" +
	"\x12\x1a\n" +
	"\x16REVIEW_STATUS_APPROVED\x10\x14\x12\x1a\n" +
	"\x16REVIEW_STATUS_REJECTED\x10\x1e\x12\x18\n" +
	"\x14REVIEW_STATUS_HIDDEN\x10(*\x80\x01\n" +
	"\fAppealStatus\x12\x1d\n" +
	"\x19APPEAL_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15APPEAL_STATUS_PENDING\x10\n" +
	"\x12\x1a\n" +
	"\x16APPEAL_STATUS_APPROVED\x10\x14\x12\x1a\n" +
	"\x16APPEAL_STATUS_REJECTED\x10\x1e*\x82\x01\n" +
	"\n" +
	"ReviewSort\x12\x1b\n" +
	"\x17REVIEW_SORT_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cREVIEW_SORT_CREATE_TIME_DESC\x10\x01\x12\x19\n" +
	"\x15REVIEW_SORT_SCORE_ASC\x10\x02\x12\x1a\n" +
	"\x16REVIEW_SORT_SCORE_DESC\x10\x032\xec\x03\n" +
	"\bConsumer\x12p\n" +
	"\fCreateReview\x12$.api.consumer.v1.CreateReviewRequest\x1a\".api.consumer.v1.CreateReviewReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/reviews\x12p\n" +
	"\tGetReview\x12!.api.consumer.v1.GetReviewRequest\x1a\x1f.api.consumer.v1.GetReviewReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/reviews/{review_id}\x12\x8f\x01\n" +
	"\x12ListReviewByUserID\x12*.api.consumer.v1.ListReviewByUserIDRequest\x1a(.api.consumer.v1.ListReviewByUserIDReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/users/{user_id}/reviews\x12j\n" +
	"\vListReviews\x12#.api.consumer.v1.ListReviewsRequest\x1a!.api.consumer.v1.ListReviewsReply\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/reviewsB0\n" +
	"\x0fapi.consumer.v1P\x01Z\x1breview-c/api/consumer/v1;v1b\x06proto3"

var (
	file_api_consumer_v1_consumer_proto_rawDescOnce sync.Once
	file_api_consumer_v1_consumer_proto_rawDescData []byte
)

func file_api_consumer_v1_consumer_proto_rawDescGZIP() []byte {
	file_api_consumer_v1_consumer_proto_rawDescOnce.Do(func() {
		file_api_consumer_v1_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_consumer_v1_consumer_proto_rawDesc), len(file_api_consumer_v1_consumer_proto_rawDesc)))
	})
	return file_api_consumer_v1_consumer_proto_rawDescData
}

var file_api_consumer_v1_consumer_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_consumer_v1_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_consumer_v1_consumer_proto_goTypes = []any{
	(ReviewStatus)(0),                 // 0: api.consumer.v1.ReviewStatus
	(AppealStatus)(0),                 // 1: api.consumer.v1.AppealStatus
	(ReviewSort)(0),                   // 2: api.consumer.v1.ReviewSort
	(*PaginationReply)(nil),           // 3: api.consumer.v1.PaginationReply
	(*ReviewSummary)(nil),             // 4: api.consumer.v1.ReviewSummary
	(*ReplyInfo)(nil),                 // 5: api.consumer.v1.ReplyInfo
	(*ReviewDetail)(nil),              // 6: api.consumer.v1.ReviewDetail
	(*CreateReviewRequest)(nil),       // 7: api.consumer.v1.CreateReviewRequest
	(*CreateReviewReply)(nil),         // 8: api.consumer.v1.CreateReviewReply
	(*GetReviewRequest)(nil),          // 9: api.consumer.v1.GetReviewRequest
	(*GetReviewReply)(nil),            // 10: api.consumer.v1.GetReviewReply
	(*ListReviewByUserIDRequest)(nil), // 11: api.consumer.v1.ListReviewByUserIDRequest
	(*ListReviewByUserIDReply)(nil),   // 12: api.consumer.v1.ListReviewByUserIDReply
	(*ListReviewsRequest)(nil),        // 13: api.consumer.v1.ListReviewsRequest
	(*ListReviewsReply)(nil),          // 14: api.consumer.v1.ListReviewsReply
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
}
var file_api_consumer_v1_consumer_proto_depIdxs = []int32{
	0,  // 0: api.consumer.v1.ReviewSummary.status:type_name -> api.consumer.v1.ReviewStatus
	15, // 1: api.consumer.v1.ReviewSummary.create_time:type_name -> google.protobuf.Timestamp
	15, // 2: api.consumer.v1.ReviewSummary.update_time:type_name -> google.protobuf.Timestamp
	15, // 3: api.consumer.v1.ReplyInfo.create_time:type_name -> google.protobuf.Timestamp
	15, // 4: api.consumer.v1.ReplyInfo.update_time:type_name -> google.protobuf.Timestamp
	4,  // 5: api.consumer.v1.ReviewDetail.summary:type_name -> api.consumer.v1.ReviewSummary
	5,  // 6: api.consumer.v1.ReviewDetail.replies:type_name -> api.consumer.v1.ReplyInfo
	6,  // 7: api.consumer.v1.GetReviewReply.review:type_name -> api.consumer.v1.ReviewDetail
	4,  // 8: api.consumer.v1.ListReviewByUserIDReply.list:type_name -> api.consumer.v1.ReviewSummary
	3,  // 9: api.consumer.v1.ListReviewByUserIDReply.page:type_name -> api.consumer.v1.PaginationReply
	2,  // 10: api.consumer.v1.ListReviewsRequest.sort:type_name -> api.consumer.v1.ReviewSort
	4,  // 11: api.consumer.v1.ListReviewsReply.list:type_name -> api.consumer.v1.ReviewSummary
	3,  // 12: api.consumer.v1.ListReviewsReply.page:type_name -> api.consumer.v1.PaginationReply
	7,  // 13: api.consumer.v1.Consumer.CreateReview:input_type -> api.consumer.v1.CreateReviewRequest
	9,  // 14: api.consumer.v1.Consumer.GetReview:input_type -> api.consumer.v1.GetReviewRequest
	11, // 15: api.consumer.v1.Consumer.ListReviewByUserID:input_type -> api.consumer.v1.ListReviewByUserIDRequest
	13, // 16: api.consumer.v1.Consumer.ListReviews:input_type -> api.consumer.v1.ListReviewsRequest
	8,  // 17: api.consumer.v1.Consumer.CreateReview:output_type -> api.consumer.v1.CreateReviewReply
	10, // 18: api.consumer.v1.Consumer.GetReview:output_type -> api.consumer.v1.GetReviewReply
	12, // 19: api.consumer.v1.Consumer.ListReviewByUserID:output_type -> api.consumer.v1.ListReviewByUserIDReply
	14, // 20: api.consumer.v1.Consumer.ListReviews:output_type -> api.consumer.v1.ListReviewsReply
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_consumer_v1_consumer_proto_init() }
func file_api_consumer_v1_consumer_proto_init() {
	if File_api_consumer_v1_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_consumer_v1_consumer_proto_rawDesc), len(file_api_consumer_v1_consumer_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_consumer_v1_consumer_proto_goTypes,
		DependencyIndexes: file_api_consumer_v1_consumer_proto_depIdxs,
		EnumInfos:         file_api_consumer_v1_consumer_proto_enumTypes,
		MessageInfos:      file_api_consumer_v1_consumer_proto_msgTypes,
	}.Build()
	File_api_consumer_v1_consumer_proto = out.File
	file_api_consumer_v1_consumer_proto_goTypes = nil
	file_api_consumer_v1_consumer_proto_depIdxs = nil
}
