// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: api/consumer/v1/consumer.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Consumer_CreateReview_FullMethodName       = "/api.consumer.v1.Consumer/CreateReview"
	Consumer_GetReview_FullMethodName          = "/api.consumer.v1.Consumer/GetReview"
	Consumer_ListReviewByUserID_FullMethodName = "/api.consumer.v1.Consumer/ListReviewByUserID"
	Consumer_ListReviews_FullMethodName        = "/api.consumer.v1.Consumer/ListReviews"
)

// ConsumerClient is the client API for Consumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Consumer —— 评价中台 C 端（消费者）对外 HTTP 契约。
// - 仅暴露 C 端发评 / 看评相关的 4 个 RPC：CreateReview / GetReview / ListReviewByUserID / ListReviews。
// - 内部通过 gRPC 调 review-service；本层做 PB↔PB 转换与 caller_role=CALLER_ROLE_C 注入。
// - 字段名与 github.com/huicod/reviewapis/review/v1/review.proto 1:1 对齐以减少转换代码。
// - 越权防护：user_id 一致性校验在 HTTP 中间件做（path.user_id == X-User-Id），这里不写。
type ConsumerClient interface {
	// [REQ-001] C 端创建评价（按 order_id 幂等，下游保证）
	CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewReply, error)
	// [REQ-002] C 端查看评价详情（非 APPROVED 会被下游折叠为 NotFound；匿名评价 user_id=0）
	GetReview(ctx context.Context, in *GetReviewRequest, opts ...grpc.CallOption) (*GetReviewReply, error)
	// [REQ-003] C 端"我的评价"列表（含待审/驳回状态，下游按 role=C 隐式处理）
	ListReviewByUserID(ctx context.Context, in *ListReviewByUserIDRequest, opts ...grpc.CallOption) (*ListReviewByUserIDReply, error)
	// [REQ-003] C 端按条件列表（仅 APPROVED；筛选子集见下方 ListReviewsRequest）
	ListReviews(ctx context.Context, in *ListReviewsRequest, opts ...grpc.CallOption) (*ListReviewsReply, error)
}

type consumerClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumerClient(cc grpc.ClientConnInterface) ConsumerClient {
	return &consumerClient{cc}
}

func (c *consumerClient) CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReviewReply)
	err := c.cc.Invoke(ctx, Consumer_CreateReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerClient) GetReview(ctx context.Context, in *GetReviewRequest, opts ...grpc.CallOption) (*GetReviewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReviewReply)
	err := c.cc.Invoke(ctx, Consumer_GetReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerClient) ListReviewByUserID(ctx context.Context, in *ListReviewByUserIDRequest, opts ...grpc.CallOption) (*ListReviewByUserIDReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReviewByUserIDReply)
	err := c.cc.Invoke(ctx, Consumer_ListReviewByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerClient) ListReviews(ctx context.Context, in *ListReviewsRequest, opts ...grpc.CallOption) (*ListReviewsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReviewsReply)
	err := c.cc.Invoke(ctx, Consumer_ListReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerServer is the server API for Consumer service.
// All implementations must embed UnimplementedConsumerServer
// for forward compatibility.
//
// Consumer —— 评价中台 C 端（消费者）对外 HTTP 契约。
// - 仅暴露 C 端发评 / 看评相关的 4 个 RPC：CreateReview / GetReview / ListReviewByUserID / ListReviews。
// - 内部通过 gRPC 调 review-service；本层做 PB↔PB 转换与 caller_role=CALLER_ROLE_C 注入。
// - 字段名与 github.com/huicod/reviewapis/review/v1/review.proto 1:1 对齐以减少转换代码。
// - 越权防护：user_id 一致性校验在 HTTP 中间件做（path.user_id == X-User-Id），这里不写。
type ConsumerServer interface {
	// [REQ-001] C 端创建评价（按 order_id 幂等，下游保证）
	CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewReply, error)
	// [REQ-002] C 端查看评价详情（非 APPROVED 会被下游折叠为 NotFound；匿名评价 user_id=0）
	GetReview(context.Context, *GetReviewRequest) (*GetReviewReply, error)
	// [REQ-003] C 端"我的评价"列表（含待审/驳回状态，下游按 role=C 隐式处理）
	ListReviewByUserID(context.Context, *ListReviewByUserIDRequest) (*ListReviewByUserIDReply, error)
	// [REQ-003] C 端按条件列表（仅 APPROVED；筛选子集见下方 ListReviewsRequest）
	ListReviews(context.Context, *ListReviewsRequest) (*ListReviewsReply, error)
	mustEmbedUnimplementedConsumerServer()
}

// UnimplementedConsumerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsumerServer struct{}

func (UnimplementedConsumerServer) CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReview not implemented")
}
func (UnimplementedConsumerServer) GetReview(context.Context, *GetReviewRequest) (*GetReviewReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReview not implemented")
}
func (UnimplementedConsumerServer) ListReviewByUserID(context.Context, *ListReviewByUserIDRequest) (*ListReviewByUserIDReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReviewByUserID not implemented")
}
func (UnimplementedConsumerServer) ListReviews(context.Context, *ListReviewsRequest) (*ListReviewsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReviews not implemented")
}
func (UnimplementedConsumerServer) mustEmbedUnimplementedConsumerServer() {}
func (UnimplementedConsumerServer) testEmbeddedByValue()                  {}

// UnsafeConsumerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsumerServer will
// result in compilation errors.
type UnsafeConsumerServer interface {
	mustEmbedUnimplementedConsumerServer()
}

func RegisterConsumerServer(s grpc.ServiceRegistrar, srv ConsumerServer) {
	// If the following call panics, it indicates UnimplementedConsumerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Consumer_ServiceDesc, srv)
}

func _Consumer_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consumer_CreateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).CreateReview(ctx, req.(*CreateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consumer_GetReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).GetReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consumer_GetReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).GetReview(ctx, req.(*GetReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consumer_ListReviewByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReviewByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).ListReviewByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consumer_ListReviewByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).ListReviewByUserID(ctx, req.(*ListReviewByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consumer_ListReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).ListReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consumer_ListReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).ListReviews(ctx, req.(*ListReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Consumer_ServiceDesc is the grpc.ServiceDesc for Consumer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Consumer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.consumer.v1.Consumer",
	HandlerType: (*ConsumerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReview",
			Handler:    _Consumer_CreateReview_Handler,
		},
		{
			MethodName: "GetReview",
			Handler:    _Consumer_GetReview_Handler,
		},
		{
			MethodName: "ListReviewByUserID",
			Handler:    _Consumer_ListReviewByUserID_Handler,
		},
		{
			MethodName: "ListReviews",
			Handler:    _Consumer_ListReviews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/consumer/v1/consumer.proto",
}
